# SPDX-License-Identifier: AGPL-3.0-only
"""dnscheck: parsers, the diagnosis table, host I/O via fixtures, and the CLI contract. No real resolver is touched."""

from __future__ import annotations

import ast
import io
import subprocess
import sys
from pathlib import Path

import pytest

from openvpn3_mcp import dnscheck
from openvpn3_mcp.dnscheck import FAIL, OK, UNKNOWN_OWNER, WARN, Lookup, ResolvConf

MEMORYDB = "clustercfg.example-cluster.abc123.memorydb.us-east-1.amazonaws.com"
HOSTS_LINE = "files mdns4_minimal [NOTFOUND=return] dns"

TAILSCALE_RESOLV = """\
# resolv.conf(5) file generated by tailscale
# For more info, see https://tailscale.com/s/resolvconf-overwrite
# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN

nameserver 100.100.100.100
nameserver fd7a:115c:a1e0::53
search example-tailnet.ts.net
"""
STUB_RESOLV = """\
# This is /run/systemd/resolve/stub-resolv.conf managed by man:systemd-resolved(8).
# Do not edit.
nameserver 127.0.0.53
options edns0 trust-ad
search example-tailnet.ts.net amazonaws.com compute.internal
"""
RESOLVECTL_DOMAIN = """\
Global: example-tailnet.ts.net
Link 2 (eth0):
Link 3 (wlan0):
Link 4 (tailscale0): example-tailnet.ts.net ~.
Link 32 (tun0): amazonaws.com compute.internal
"""
TUN_LINKS = {"tailscale0": ["example-tailnet.ts.net", "~."], "tun0": ["amazonaws.com", "compute.internal"]}

TAILSCALE = ResolvConf(owner="tailscale", nameservers=["100.100.100.100", "fd7a:115c:a1e0::53"], symlink=False)
STUB = ResolvConf(owner="systemd-resolved stub", nameservers=["127.0.0.53"], symlink=True)


# --- resolv.conf owner ------------------------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("target", "owner"),
    [
        ("/run/systemd/resolve/stub-resolv.conf", "systemd-resolved stub"),
        ("/usr/lib/systemd/resolv.conf", "systemd-resolved static stub"),
        ("/lib/systemd/resolv.conf", "systemd-resolved static stub"),
        ("/run/systemd/resolve/resolv.conf", "systemd-resolved uplink file (lists upstream servers, skips per-link routing)"),
        ("/run/NetworkManager/resolv.conf", "symlink to /run/NetworkManager/resolv.conf"),
    ],
)
def test_owner_from_symlink_target(target, owner):
    assert dnscheck.resolv_conf_owner(target, "") == owner


def test_owner_tailscale_despite_resolvconf_in_its_own_header():
    # Tailscale's header links to .../resolvconf-overwrite; tailscaled itself misreads that as resolvconf (#19062).
    assert dnscheck.resolv_conf_owner(None, TAILSCALE_RESOLV) == "tailscale"


@pytest.mark.parametrize(
    ("text", "owner"),
    [
        ("# Generated by NetworkManager\nnameserver 192.168.1.1\n", "NetworkManager"),
        ("# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)\nnameserver 10.0.0.1\n", "resolvconf"),
        (STUB_RESOLV, "copy of a systemd-resolved file"),
        ("domain corp.example\nnameserver 10.99.0.4\nnameserver 127.0.0.53\n", UNKNOWN_OWNER),
        ("nameserver 1.1.1.1\n# generated by tailscale (comment after the first directive doesn't count)\n", UNKNOWN_OWNER),
    ],
)
def test_owner_from_header_comments(text, owner):
    assert dnscheck.resolv_conf_owner(None, text) == owner


def test_parse_nameservers_ignores_comments_and_other_directives():
    text = "# nameserver 9.9.9.9\nsearch x\nnameserver 127.0.0.53  # stub\nnameserver\noptions edns0\n"
    assert dnscheck.parse_nameservers(text) == ["127.0.0.53"]


@pytest.mark.parametrize(
    ("servers", "is_stub"),
    [(["127.0.0.53"], True), (["127.0.0.53", "127.0.0.53"], True), (["127.0.0.53", "10.0.0.2"], False), (["100.100.100.100"], False), ([], False)],
)
def test_is_stub_needs_every_nameserver_on_the_stub(servers, is_stub):
    assert ResolvConf(owner="x", nameservers=servers, symlink=False).is_stub is is_stub


def test_read_resolv_conf_follows_relative_symlink(tmp_path, monkeypatch):
    (tmp_path / "run/systemd/resolve").mkdir(parents=True)
    (tmp_path / "run/systemd/resolve/stub-resolv.conf").write_text(STUB_RESOLV)
    (tmp_path / "etc").mkdir()
    (tmp_path / "etc/resolv.conf").symlink_to("../run/systemd/resolve/stub-resolv.conf")
    monkeypatch.setattr(dnscheck, "RESOLV_CONF", tmp_path / "etc/resolv.conf")
    got = dnscheck.read_resolv_conf()
    assert (got.owner, got.nameservers, got.symlink, got.is_stub) == ("systemd-resolved stub", ["127.0.0.53"], True, True)


def test_read_resolv_conf_dangling_symlink_is_not_a_stub(tmp_path, monkeypatch):
    (tmp_path / "resolv.conf").symlink_to(tmp_path / "missing/run/systemd/resolve/stub-resolv.conf")
    monkeypatch.setattr(dnscheck, "RESOLV_CONF", tmp_path / "resolv.conf")
    got = dnscheck.read_resolv_conf()
    assert got.owner == "systemd-resolved stub"
    assert not got.is_stub


# --- nsswitch / hosts / netcfg ----------------------------------------------------------------------------------


def test_nsswitch_hosts_line_strips_comments_and_whitespace():
    text = "# hosts: resolve dns\npasswd: files\nhosts:          files mdns4_minimal [NOTFOUND=return] dns   # default\nnetworks: files\n"
    assert dnscheck.nsswitch_hosts(text) == HOSTS_LINE
    assert dnscheck.nsswitch_hosts("passwd: files\n") is None


def test_nsswitch_last_hosts_line_wins_like_glibc():
    text = "hosts: files resolve [!UNAVAIL=return] dns\npasswd: files\nhosts : files mdns4_minimal [NOTFOUND=return] dns\n"
    assert dnscheck.nsswitch_hosts(text) == HOSTS_LINE


@pytest.mark.parametrize(
    ("line", "services", "first"),
    [
        (HOSTS_LINE, ["files", "mdns4_minimal", "dns"], False),
        ("files mdns4_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns", ["files", "mdns4_minimal", "resolve", "dns"], True),
        ("mymachines resolve [!UNAVAIL=return] files myhostname dns", ["mymachines", "resolve", "files", "myhostname", "dns"], True),
        ("files dns resolve", ["files", "dns", "resolve"], False),
        ("files resolve [NOTFOUND=return  UNAVAIL=continue]", ["files", "resolve"], True),
    ],
)
def test_nss_services_and_resolve_order(line, services, first):
    assert dnscheck.nss_services(line) == services
    assert dnscheck.resolve_before_dns(services) is first


def test_hosts_pins_matches_aliases_case_insensitively():
    text = f"127.0.0.1 localhost\n# 10.9.9.9 {MEMORYDB}\n10.0.12.34 {MEMORYDB.upper()}. alias\n10.0.0.5 other.example\n"
    assert dnscheck.hosts_pins(text, MEMORYDB) == ["10.0.12.34"]
    assert dnscheck.hosts_pins(text, "alias") == ["10.0.12.34"]
    assert dnscheck.hosts_pins(text, "absent.example") == []


@pytest.mark.parametrize(
    ("text", "value"),
    [
        ('{\n\t//  Option --systemd-resolved :: Systemd-resolved in use\n\t"systemd_resolved" : true\n}\n', "true"),
        ('{"systemd_resolved": false, "x": 1}', "false"),
        ("{}", None),
    ],
)
def test_netcfg_systemd_resolved(text, value):
    assert dnscheck.netcfg_systemd_resolved(text) == value


# --- resolvectl / getent output -----------------------------------------------------------------------------------


def test_parse_link_domains_keeps_links_with_domains():
    assert dnscheck.parse_link_domains(RESOLVECTL_DOMAIN) == TUN_LINKS


@pytest.mark.parametrize(
    ("host", "route"),
    [
        (MEMORYDB, ("tun0", "amazonaws.com")),
        ("ip-10-0-0-5.ec2.compute.internal", ("tun0", "compute.internal")),
        ("box.example-tailnet.ts.net.", ("tailscale0", "example-tailnet.ts.net")),
        ("github.com", None),  # only tailscale0's "~." matches, and that isn't a split-DNS domain
        ("notamazonaws.com", None),
    ],
)
def test_route_for(host, route):
    assert dnscheck.route_for(host, TUN_LINKS) == route


def test_route_for_prefers_the_domain_with_most_labels():
    links = {"tun0": ["amazonaws.com"], "tun1": ["us-east-1.amazonaws.com"]}
    assert dnscheck.route_for(MEMORYDB, links) == ("tun1", "us-east-1.amazonaws.com")


def test_parse_resolvectl_query():
    out = f"{MEMORYDB}: 10.0.12.34                    -- link: tun0\n    10.0.12.35                    -- link: tun0\n    fd00::1   -- link: tun0\n    (cname.example)\n"
    assert dnscheck.parse_resolvectl_query(out) == (["10.0.12.34", "10.0.12.35", "fd00::1"], ["tun0"])


def test_parse_getent_ahosts_dedupes_socket_types():
    out = f"10.0.12.34     STREAM {MEMORYDB}\n10.0.12.34     DGRAM  \n10.0.12.34     RAW    \n::1 STREAM\n"
    assert dnscheck.parse_getent_ahosts(out) == (["10.0.12.34", "::1"], [])


# --- the diagnosis table ------------------------------------------------------------------------------------------


def _decide(
    *,
    resolv: ResolvConf = TAILSCALE,
    hosts_line: str | None = HOSTS_LINE,
    nss_resolve: bool = False,
    links: dict[str, list[str]] | None = TUN_LINKS,
    host: str | None = None,
    resolved: Lookup | None = None,
    nss: Lookup | None = None,
    pins: list[str] | None = None,
    connected: bool = False,
) -> dnscheck.Report:
    """This host's 2026-09-25 state (Tailscale owns resolv.conf, no nss-resolve, tunnel up) unless overridden."""
    return dnscheck.decide(
        resolv=resolv, hosts_line=hosts_line, nss_resolve=nss_resolve, links=links, host=host, connected=connected, resolved=resolved, nss=nss, pins=pins, netcfg="true"
    )


def _probe(resolved: Lookup, nss: Lookup, pins: list[str] | None = None, resolv: ResolvConf = TAILSCALE) -> dnscheck.Report:
    return _decide(host=MEMORYDB, resolved=resolved, nss=nss, pins=pins, resolv=resolv)


def _fix_text(report):
    return "\n".join(report.fix)


def test_filtered_answer_is_fail_with_the_tailscale_fix():
    # The 2026-09-25 incident: resolved gets the private IP via tun0, programs get 0.0.0.0 from quad-100/NextDNS.
    report = _probe(Lookup(["10.0.12.34"], links=["tun0"]), Lookup(["0.0.0.0"]))
    assert report.verdict == FAIL
    assert "Programs get 0.0.0.0" in report.reason
    assert "filtered" in report.reason
    fix = _fix_text(report)
    assert "sudo ln -sfn ../run/systemd/resolve/stub-resolv.conf /etc/resolv.conf" in fix
    assert "sudo systemctl restart tailscaled" in fix
    assert "sudo apt install libnss-resolve" in fix


def test_pin_that_agrees_is_warn_when_programs_bypass_resolved():
    report = _probe(Lookup(["10.0.12.34"], links=["tun0"]), Lookup(["10.0.12.34"]), pins=["10.0.12.34"])
    assert report.verdict == WARN
    assert "only because /etc/hosts pins it" in report.reason
    assert "Other names under amazonaws.com" in report.reason
    assert "cluster endpoint" in report.reason
    assert report.fix


def test_pin_that_agrees_is_ok_when_programs_reach_resolved():
    report = _probe(Lookup(["10.0.12.34"], links=["tun0"]), Lookup(["10.0.12.34"]), pins=["10.0.12.34"], resolv=STUB)
    assert report.verdict == OK
    assert report.fix == []


def test_stale_pin_is_fail():
    report = _probe(Lookup(["10.0.91.7"], links=["tun0"]), Lookup(["10.0.12.34"]), pins=["10.0.12.34"], resolv=STUB)
    assert report.verdict == FAIL
    assert "the pin is stale" in report.reason


def test_pin_to_unspecified_address_is_blamed_on_the_pin():
    report = _probe(Lookup(["10.0.12.34"], links=["tun0"]), Lookup(["0.0.0.0"]), pins=["0.0.0.0"], resolv=STUB)
    assert report.verdict == FAIL
    assert "/etc/hosts pins it there" in report.reason


def test_healthy_stub_agrees():
    report = _probe(Lookup(["10.0.12.34"], links=["tun0"]), Lookup(["10.0.12.34"]), resolv=STUB)
    assert (report.verdict, report.fix) == (OK, [])
    assert "agree" in report.reason


def test_agreement_without_reaching_resolved_is_ok_but_says_so():
    report = _probe(Lookup(["10.0.12.34"], links=["tun0"]), Lookup(["10.0.12.34"]))
    assert report.verdict == OK
    assert "gave the same answer this time" in report.reason


def test_programs_not_found_is_fail():
    report = _probe(Lookup(["10.0.12.34"], links=["tun0"]), Lookup(error="not found"))
    assert report.verdict == FAIL
    assert "Programs can't resolve" in report.reason


def test_neither_path_resolves_is_fail_without_layer2_fix_when_programs_reach_resolved():
    report = _probe(Lookup(error="resolve call failed: not found"), Lookup(error="not found"), resolv=STUB)
    assert report.verdict == FAIL
    assert "doesn't resolve on either path" in report.reason
    assert report.fix == []


def test_different_answers_under_a_tunnel_domain_is_fail():
    report = _probe(Lookup(["10.0.12.34"], links=["tun0"]), Lookup(["203.0.113.9"]))
    assert report.verdict == FAIL
    assert "via tun0" in report.reason


def test_host_outside_every_tunnel_domain_is_warn_without_a_comparison():
    # Tunnel down (doctor's usual state) or a VPN that pushes no domain: comparing would blame the wrong thing.
    report = _decide(host="db.private.example", links={"tailscale0": ["example-tailnet.ts.net", "~."]})
    assert report.verdict == WARN
    assert "the tunnel is down, or the VPN doesn't push a DNS domain" in report.reason
    assert ("lookup", "db.private.example -> no link's DNS domain covers it; not compared") in report.facts
    assert "sudo apt install libnss-resolve" in _fix_text(report)


def test_resolved_failing_but_programs_resolving_is_warn():
    report = _probe(Lookup(error="no answer within 15s"), Lookup(["10.0.12.34"]))
    assert report.verdict == WARN


def test_resolved_failing_with_a_pin_uses_the_pin_wording():
    # The skill turns any "/etc/hosts pins it" WARN into a FAIL for cluster clients; both pin WARNs must say it.
    report = _probe(Lookup(error="no answer within 15s"), Lookup(["10.0.12.34"]), pins=["10.0.12.34"])
    assert report.verdict == WARN
    assert "because /etc/hosts pins it" in report.reason


@pytest.mark.parametrize(
    ("nss", "verdict", "phrase"),
    [
        (Lookup(["0.0.0.0"]), FAIL, "Programs get 0.0.0.0"),
        (Lookup(error="no answer (not found, or the resolver in /etc/resolv.conf didn't respond)"), FAIL, "Programs can't resolve"),
        (Lookup(["198.51.100.7"]), WARN, "Programs get 198.51.100.7"),
    ],
)
def test_connected_but_unrouted_host_is_judged_by_what_programs_get(nss, verdict, phrase):
    # After connecting, "the tunnel might be down" is ruled out: a VPN that pushes no domain for the host must not pass.
    report = _decide(host="db.private.example", connected=True, nss=nss, links={"tailscale0": ["example-tailnet.ts.net", "~."], "tun0": ["~."]})
    assert report.verdict == verdict
    assert phrase in report.reason
    assert "the VPN has to push a DNS domain for it" in report.reason


def test_resolved_itself_unspecified_blames_the_tunnel_dns():
    report = _probe(Lookup(["0.0.0.0"], links=["tun0"]), Lookup(["0.0.0.0"]), resolv=STUB)
    assert report.verdict == FAIL
    assert "systemd-resolved itself answers 0.0.0.0" in report.reason
    assert "from the DNS on tun0" in report.reason


@pytest.mark.parametrize("resolv", [STUB, ResolvConf(owner="systemd-resolved static stub", nameservers=["127.0.0.53"], symlink=True)])
def test_no_host_ok_when_resolv_conf_is_a_stub(resolv):
    assert _decide(resolv=resolv).verdict == OK


def test_no_host_ok_through_nss_resolve():
    report = _decide(hosts_line="files resolve [!UNAVAIL=return] dns", nss_resolve=True)
    assert report.verdict == OK
    assert any("through nss-resolve" in value for _, value in report.facts)


def test_no_host_warn_names_the_tunnel_domains():
    report = _decide()
    assert report.verdict == WARN
    assert "amazonaws.com, compute.internal" in report.reason
    assert "sudo systemctl restart tailscaled" in _fix_text(report)


def test_resolve_in_nsswitch_without_the_library_does_not_count():
    report = _decide(hosts_line="files resolve [!UNAVAIL=return] dns", nss_resolve=False)
    assert report.verdict == WARN
    assert any("libnss_resolve.so.2 isn't installed" in value for _, value in report.facts)


def test_uplink_symlink_is_not_enough():
    uplink = ResolvConf(owner="systemd-resolved uplink file (lists upstream servers, skips per-link routing)", nameservers=["100.100.100.100", "192.0.2.1"], symlink=True)
    report = _decide(resolv=uplink)
    assert report.verdict == WARN
    fix = _fix_text(report)
    assert "stub-resolv.conf" in fix
    assert "tailscaled" not in fix


@pytest.mark.parametrize(
    ("owner", "hint"),
    [("NetworkManager", "dns=systemd-resolved"), (UNKNOWN_OWNER, "disconnect it first")],
)
def test_owner_specific_fix_hints(owner, hint):
    report = _decide(resolv=ResolvConf(owner=owner, nameservers=["10.99.0.4"], symlink=False))
    assert hint in _fix_text(report)


def test_ip_literal_needs_no_lookup():
    report = _decide(host="10.0.12.34", resolv=STUB)
    assert report.verdict == OK
    assert "IP address" in report.reason


def test_systemd_resolved_not_running_is_a_skip():
    report = _decide(links=None)
    assert report.verdict == OK
    assert report.reason.startswith("SKIP")


def test_systemd_resolved_unreachable_is_warn_not_skip():
    report = dnscheck.decide(resolv=TAILSCALE, hosts_line=HOSTS_LINE, nss_resolve=False, links=None, resolved_error="sd_bus_open_system: No such file or directory")
    assert report.verdict == WARN
    assert "Couldn't query systemd-resolved (sd_bus_open_system" in report.reason
    assert report.fix


# --- host I/O through fixtures ------------------------------------------------------------------------------------


@pytest.fixture
def fake_host(tmp_path, monkeypatch):
    """Point every file at tmp_path fixtures and route subprocess calls through a table; returns (files, calls, answers)."""
    files = {
        "RESOLV_CONF": tmp_path / "resolv.conf",
        "NSSWITCH_CONF": tmp_path / "nsswitch.conf",
        "HOSTS_FILE": tmp_path / "hosts",
        "NETCFG_JSON": tmp_path / "netcfg.json",
    }
    files["RESOLV_CONF"].write_text(TAILSCALE_RESOLV)
    files["NSSWITCH_CONF"].write_text(f"hosts:          {HOSTS_LINE}\n")
    files["HOSTS_FILE"].write_text("127.0.0.1 localhost\n")
    files["NETCFG_JSON"].write_text('{ "systemd_resolved" : true }\n')
    for name, path in files.items():
        monkeypatch.setattr(dnscheck, name, path)
    (tmp_path / "run-resolve").mkdir()
    monkeypatch.setattr(dnscheck, "RESOLVED_RUN_DIR", tmp_path / "run-resolve")
    monkeypatch.setattr(dnscheck, "nss_resolve_installed", lambda: False)

    calls: list[list[str]] = []
    answers: dict[str, object] = {
        "resolvectl domain": (0, RESOLVECTL_DOMAIN, ""),
        "resolvectl query": (0, f"{MEMORYDB}: 10.0.12.34 -- link: tun0\n", ""),
        "getent ahosts": (0, f"0.0.0.0 STREAM {MEMORYDB}\n0.0.0.0 DGRAM\n", ""),
    }

    def fake_run(argv):
        calls.append(argv)
        answer = answers[" ".join(argv[:2])]
        if isinstance(answer, BaseException):
            raise answer
        rc, out, err = answer  # ty: ignore[not-iterable]
        return subprocess.CompletedProcess(argv, rc, out, err)

    monkeypatch.setattr(dnscheck, "_run", fake_run)
    return files, calls, answers


def test_check_runs_both_lookups_and_skips_etc_hosts_in_resolved(fake_host):
    _, calls, _ = fake_host
    report = dnscheck.check(MEMORYDB)
    assert report.verdict == FAIL
    assert ["resolvectl", "query", "--legend=no", "--synthesize=no", MEMORYDB] in calls
    assert ["getent", "ahosts", MEMORYDB] in calls


def test_check_reads_the_pin(fake_host):
    files, _, answers = fake_host
    files["HOSTS_FILE"].write_text(f"127.0.0.1 localhost\n10.0.12.34 {MEMORYDB}\n")
    answers["getent ahosts"] = (0, f"10.0.12.34 STREAM {MEMORYDB}\n", "")
    report = dnscheck.check(MEMORYDB)
    assert report.verdict == WARN
    assert ("  programs", "10.0.12.34 (/etc/hosts pins 10.0.12.34)") in report.facts


def test_check_maps_getent_exit_2_and_timeouts(fake_host):
    _, _, answers = fake_host
    answers["getent ahosts"] = (2, "", "")
    answers["resolvectl query"] = subprocess.TimeoutExpired(["resolvectl"], dnscheck.LOOKUP_TIMEOUT_SECS)
    report = dnscheck.check(MEMORYDB)
    assert report.verdict == FAIL
    assert ("  programs", "none: no answer (not found, or the resolver in /etc/resolv.conf didn't respond)") in report.facts
    assert ("  resolved", "none: no answer within 15s") in report.facts


def test_check_resolvectl_error_keeps_last_stderr_line(fake_host):
    _, _, answers = fake_host
    answers["resolvectl query"] = (1, "", f"{MEMORYDB}: resolve call failed: '{MEMORYDB}' not found\n")
    answers["getent ahosts"] = (2, "", "")
    report = dnscheck.check(MEMORYDB)
    assert ("  resolved", f"none: {MEMORYDB}: resolve call failed: '{MEMORYDB}' not found") in report.facts


def test_check_without_resolvectl_skips(fake_host):
    _, calls, answers = fake_host
    answers["resolvectl domain"] = FileNotFoundError(2, "No such file or directory")
    report = dnscheck.check(MEMORYDB)
    assert report.verdict == OK
    assert report.reason.startswith("SKIP")
    assert calls == [["resolvectl", "domain"]]  # no lookups once resolved is known to be absent


@pytest.mark.parametrize(
    "failure",
    [(1, "", "sd_bus_open_system: No such file or directory\n"), subprocess.TimeoutExpired(["resolvectl", "domain"], dnscheck.LOOKUP_TIMEOUT_SECS)],
)
def test_check_resolvectl_failing_while_resolved_exists_is_warn(fake_host, failure):
    _, calls, answers = fake_host
    answers["resolvectl domain"] = failure
    report = dnscheck.check(MEMORYDB)
    assert report.verdict == WARN
    assert "Couldn't query systemd-resolved" in report.reason
    assert calls == [["resolvectl", "domain"]]


def test_check_resolvectl_failing_without_resolved_runtime_dir_is_skip(fake_host, tmp_path, monkeypatch):
    _, _, answers = fake_host
    answers["resolvectl domain"] = (1, "", "Failed to get global data: Unit dbus-org.freedesktop.resolve1.service not found.\n")
    monkeypatch.setattr(dnscheck, "RESOLVED_RUN_DIR", tmp_path / "absent")
    assert dnscheck.check(MEMORYDB).reason.startswith("SKIP")


def test_check_skips_lookups_for_a_host_no_link_routes(fake_host):
    _, calls, _ = fake_host
    assert dnscheck.check("github.com").verdict == WARN
    assert calls == [["resolvectl", "domain"]]


def test_check_connected_asks_programs_path_for_an_unrouted_host(fake_host):
    _, calls, answers = fake_host
    answers["getent ahosts"] = (0, "0.0.0.0 STREAM db.private.example\n", "")
    assert dnscheck.check("db.private.example", connected=True).verdict == FAIL
    assert calls == [["resolvectl", "domain"], ["getent", "ahosts", "db.private.example"]]


def test_check_without_host_runs_no_lookups(fake_host):
    _, calls, _ = fake_host
    assert dnscheck.check(None).verdict == WARN
    assert calls == [["resolvectl", "domain"]]


def test_check_tolerates_missing_files(fake_host):
    files, _, _ = fake_host
    for path in files.values():
        path.unlink()
    report = dnscheck.check(None)
    assert ("nsswitch", "no hosts: line") in report.facts
    assert ("netcfg", "no systemd_resolved setting (see check 4)") in report.facts


# --- CLI contract -------------------------------------------------------------------------------------------------


@pytest.mark.parametrize(("verdict", "code"), [(OK, 0), (FAIL, 1), (WARN, 3)])
def test_main_exit_codes(monkeypatch, capsys, verdict, code):
    monkeypatch.setattr(dnscheck, "check", lambda host, connected=False: dnscheck.Report([("k", "v")], verdict, "because", ["fix line"]))
    assert dnscheck.main([MEMORYDB]) == code
    out = capsys.readouterr().out
    assert f"{verdict}  because" in out
    assert "fix line" in out


@pytest.mark.parametrize("arg", ["x;rm -rf /", "$(id)", "-bad", "a b", "", "db.example\n", ".leading-dot"])
def test_main_rejects_non_hostnames(arg):
    with pytest.raises(SystemExit) as exc:
        dnscheck.main([arg])
    assert exc.value.code == 2


@pytest.mark.parametrize(
    "argv",
    [[f"rediss://user:s3cr3t@{MEMORYDB}:6379"], [MEMORYDB, f"rediss://user:s3cr3t@{MEMORYDB}:6379"], ["--url=rediss://user:s3cr3t@x:1"]],
)
def test_main_never_echoes_rejected_arguments(capsys, argv):
    with pytest.raises(SystemExit) as exc:
        dnscheck.main(argv)
    assert exc.value.code == 2
    err = capsys.readouterr().err
    assert "s3cr3t" not in err
    assert "pass one bare hostname" in err


@pytest.mark.parametrize(
    ("url", "host"),
    [
        (f"rediss://user:s3cr3t@{MEMORYDB}:6379", MEMORYDB),
        (f"rediss://user:Pa55#w?r/d@{MEMORYDB}:6379/0", MEMORYDB),  # unencoded '#', '?', '/' in the password
        (f"rediss://:p@ss@{MEMORYDB}:6379\n", MEMORYDB),
        (f"mysql://{MEMORYDB}/app", MEMORYDB),
        ("rediss://user:pw@[fd00::1]:6379", "fd00::1"),
        ("rediss://user:pw@[broken:6379", None),
        ("", None),
    ],
)
def test_host_from_url(url, host):
    assert dnscheck.host_from_url(url) == host


def test_main_url_stdin_checks_the_host_without_printing_the_url(monkeypatch, capsys):
    seen = []
    monkeypatch.setattr(dnscheck, "check", lambda host, connected=False: seen.append((host, connected)) or dnscheck.Report([("k", "v")], OK, "fine"))
    monkeypatch.setattr(sys, "stdin", io.StringIO(f"rediss://user:s3cr3t@{MEMORYDB}:6379\n"))
    assert dnscheck.main(["--connected", "--url-stdin"]) == 0
    assert seen == [(MEMORYDB, True)]
    assert "s3cr3t" not in capsys.readouterr().out


def test_main_url_stdin_rejects_a_url_without_a_host(monkeypatch, capsys):
    monkeypatch.setattr(sys, "stdin", io.StringIO("rediss://user:s3cr3t@\n"))
    with pytest.raises(SystemExit) as exc:
        dnscheck.main(["--url-stdin"])
    assert exc.value.code == 2
    assert "s3cr3t" not in capsys.readouterr().err


def test_main_rejects_hostname_and_url_stdin_together():
    with pytest.raises(SystemExit) as exc:
        dnscheck.main([MEMORYDB, "--url-stdin"])
    assert exc.value.code == 2


@pytest.mark.parametrize("arg", [MEMORYDB, "10.0.12.34", "fd00::1", "host_with_underscore.internal"])
def test_main_accepts_hostnames_and_ips(monkeypatch, arg):
    monkeypatch.setattr(dnscheck, "check", lambda host, connected=False: dnscheck.Report([("k", "v")], OK, "fine"))
    assert dnscheck.main([arg]) == 0


def test_standard_library_only():
    # doctor, setup and the skill run this file with the system python3, outside the venv.
    tree = ast.parse(Path(dnscheck.__file__).read_text())
    imported = {alias.name.split(".")[0] for node in ast.walk(tree) if isinstance(node, ast.Import) for alias in node.names}
    imported |= {node.module.split(".")[0] for node in ast.walk(tree) if isinstance(node, ast.ImportFrom) and node.module and node.level == 0}
    assert not any(isinstance(node, ast.ImportFrom) and node.level for node in ast.walk(tree)), "relative imports break running by path"
    assert imported - {"__future__"} <= set(sys.stdlib_module_names)


def test_runs_by_path_in_isolated_mode():
    proc = subprocess.run([sys.executable, "-I", dnscheck.__file__, "--help"], capture_output=True, text=True, check=False)
    assert proc.returncode == 0, proc.stderr
    assert "Exit status: 0 OK, 1 FAIL, 3 WARN, 2 bad usage" in proc.stdout
